---
title: "data_pre_processing"
author: "Cihan ERMAN"
date: "6/2/2019"
output: html_document
---
```{r}
df <- data.frame(
  V1 = c(1,3,6,NA,7,1,NA,9,15),
  V2 = c(7,NA,5,9,12,NA,NA,2,3),
  V3 = c(NA,12,5,6,3,7,2,NA,99)
)
```
```{r}
na.omit(df)
df$V1[is.na(df$V1)] <- mean(df$V1, na.rm = T)
sapply(df, function(x) ifelse(is.na(x), mean(x, na.rm = T), x ))
```      
```{r}
is.na(df)
sum(is.na(df))
colSums(is.na(df))
which(is.na(df))
```

```{r}
complete.cases(df)
df[complete.cases(df),]
df[!complete.cases(df),]
df[!complete.cases(df),]$V1
df$V3[df$V3 == 99] <- NA
```

```{r}
library(ISLR)
df <- Hitters
str(df)
colSums(is.na(df))
df[sample(1:nrow(df), 7), "Hits"] <- NA
df[sample(1:nrow(df), 9), "Runs"] <- NA
df[sample(1:nrow(df), 5), "RBI"] <- NA
df[, c("Salary", "Hits", "Runs", "RBI")]
df[!complete.cases(df),]
library(mice)
md.pattern(df)
md.pattern(df[, c("Salary", "Hits", "Runs", "RBI")])
```
```{r}
library(VIM)
library(ISLR)
df <- Hitters
str(df)
colSums(is.na(df))
df[sample(1:nrow(df), 7), "Hits"] <- NA
df[sample(1:nrow(df), 9), "Runs"] <- NA
df[sample(1:nrow(df), 5), "RBI"] <- NA

aggr_plot <- aggr(df, col=c('navyblue','red'), 
                  numbers = TRUE, 
                  sortVars = TRUE, 
                  labels = names(df), 
                  cex.axis=.7, 
                  gap=3, 
                  ylab=c("Eksik Degerlerin Oransal Gosterimi",
                         "Eksikligin Veri Seti Icindeki Yapisi"))


aggr_plot
```
```{r}
library(BaylorEdPsych)
library(mvnmle)
t <- LittleMCAR(df)
attributes(t)

```
```{r}
na.omit(df)
sapply(df, function(x) sum(is.na(x)))
sapply(df[!is.na(df$Runs),], function(x) sum(is.na(x)))
df <- df[!is.na(df$Runs),]
g <- apply(df, 1, function(x) sum(is.na(x)) / length(x))
g <- as.vector(g)
df$eksik_oran <- g
str(df)
library(dplyr)
df %>% filter(df$eksik_oran < 0.01)

library(funModeling)
df_status(df)

df$Salary <- NULL
d <- apply(df, 2, function(x) sum(is.na(x)) / length(x))
d <- as.data.frame(d)
d$deisken_isimleri <- rownames(d)
d[d$d > 0.02,]
```

```{r}
df <- Hitters
df[sample(1:nrow(df), 7), "Hits"] <- NA
df[sample(1:nrow(df), 9), "Runs"] <- NA
df[sample(1:nrow(df), 5), "RBI"] <- NA
library(Hmisc)
df$Hits <- impute(df$Hits, mean)
summary(df$Hits)
```

```{r}
df <- Hitters
df[sample(1:nrow(df), 7), "Hits"] <- NA
df[sample(1:nrow(df), 9), "Runs"] <- NA
df[sample(1:nrow(df), 5), "RBI"] <- NA

library(DMwR) # for knn
anyNA(df)
knn_data <- knnImputation(df, k = 5, meth = "median")
anyNA(knn_data)

library(missForest) # for random forest
rf_data <- missForest(df, ntree = 7)
```

H0: Eksik Veriler Tamamen Rasgele Dagilmistir
H1: Eksik Veriler Rasgele Dagilmamistir
```{r}
# ödev
df <- mtcars
df[sample(1:nrow(df), 3), "mpg"] <- NA
df[sample(1:nrow(df), 2), "qsec"] <- NA
colSums(df)
df[complete.cases(df),]
df[!complete.cases(df),]
t <- LittleMCAR(df)
t$p.value
md.pattern(df)
aggr_plot <- aggr(df, col=c('navyblue','red'), 
                  numbers = TRUE, 
                  sortVars = TRUE, 
                  labels = names(df), 
                  cex.axis=.7, 
                  gap=3, 
                  ylab=c("Eksik Degerlerin Oransal Gosterimi",
                         "Eksikligin Veri Seti Icindeki Yapisi"))


aggr_plot
```
```{r}

```

