---
title: "data_analysis"
author: "Cihan ERMAN"
date: "20 05 2019"
output: pdf_document
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
df <- mpg
df$class <- factor(df$class)
df$displ_yeni <- ifelse(df$displ > 2, 1, 0)
df$displ_yeni <- factor(df$displ_yeni)
glimpse(df)
colnames(df)
nrow(df)
ncol(df)
head(df)
str(df)
glimpse(df)
psych::headTail(df)
summary(df)
fivenum(df$displ)
levels(df$class)

```

```{r}
library(funModeling)
profiling_num(df)
plot_num(df)
freq(df)






```

```{r}
library(psych)
describe(mpg$displ)
library(Hmisc)
Hmisc::describe(mpg$displ)
library(pastecs)
stat.desc((mpg))

df <- select(mpg, trans, cty, cyl, hwy)
describe.by(df,df$trans)
```


```{r}
library(d3Tree)
d3tree(list(root = df2tree(rootname = 'mpg',
            struct = as.data.frame(mpg)),
            layout = 'collapse'))

d3tree(list(root = df2tree(rootname = 'Titanic',
            struct = as.data.frame(Titanic)),
            layout = 'collapse'))


library(xplorerr)
app_descriptive()


```

```{r}
# kategorik değişkenler de bar plot kullanılır
df <- diamonds
glimpse(df)

ggplot(df, aes(cut)) +
    geom_bar()

ggplot(df, aes(cut, fill = color)) +
    geom_bar(position = position_dodge()) +
    ggtitle('Cut an color') +
    xlab('Kesim') +
    ylab('Adet')

```

```{r}
ggplot(df, aes(price)) +
    geom_histogram(binwidth = 1000)

ggplot(df, aes(price)) +
    geom_density()

ggplot(df, aes(price)) +
    geom_histogram(aes(y = ..density..)) +
    geom_density(alpha = .3, fill = 'orange')

ggplot(df, aes(price, fill = cut)) +
    geom_histogram()

ggplot(df, aes(price)) +
    geom_histogram() +
    facet_grid(cut ~.)
```

```{r}
library(ggridges)
ggplot(df, aes(x = price, y = cut, fill = cut)) +
    geom_density_ridges() +
    theme_ridges() + 
    theme(legend.position = 'none')
```

```{r}
library(plotly)
g <- plot_ly(x = rnorm(500), type = 'histogram')
g

g <- plot_ly(x = rnorm(500), opacity = 0.6 , type = 'histogram') %>%
    add_trace(x = rnorm(500) + 1) %>%
    layout(barmode = 'overlay')

g

```

```{r}
ggplot(df, aes(price, y = ..density..)) +
    geom_freqpoly(aes(color = cut), binwidth = 500)

ggplot(df, aes(price, y = ..density..)) +
    geom_density(aes(color = cut), binwidth = 500)
```

```{r}
ggplot(df, aes(x = cut, y = price, fill = cut)) +
    geom_boxplot()
```

```{r}
ggplot(df, aes(x = cut, y = price, fill = cut)) +
    geom_violin(alpha = 0.5)
```

```{r}
glimpse(iris)

df <- iris
ggplot(df, aes(Sepal.Length , Sepal.Width)) +
    geom_point(size = 2,
               shape = 25,
               stroke = 1,
               color = 'black',
               fill = 'orange') +
    geom_smooth( color = 'red')

ggplot(df, aes(Sepal.Length , Sepal.Width, color = Species, shape = Species)) +
    geom_point(size = 5,
               alpha = 0.5)

ggplot(df, aes(Sepal.Length , Sepal.Width, color = Petal.Length, size = Petal.Length)) +
    geom_point(alpha = 0.5)


```
```{r}
df <- mtcars
glimpse(df)

ggplot(df, aes(x = wt, y = mpg)) +
    geom_point() +
    geom_text(label = rownames(df),
              nudge_x = 0.25,
              nudge_y = 0.25,
              check_overlap = T)

ggplot(df, aes(x = wt, y = mpg, fill = cyl)) +
    geom_point() +
    geom_label(label = rownames(df),
              nudge_x = 0.25,
              nudge_y = 0.25,
              check_overlap = T) + 
    geom_smooth(method = lm, se = F)



```

```{r}
library(ggExtra)
g <- ggplot(df, aes(x = wt, y = mpg, fill = cyl)) +
    geom_point() +
    geom_label(label = rownames(df),
              nudge_x = 0.25,
              nudge_y = 0.25,
              check_overlap = T) + 
    geom_smooth(method = lm, se = F)

ggMarginal(g, type = 'histogram', fill = 'slateblue')

```

```{r}
df <- as.matrix(mtcars)
heatmap(df,Colv = NA, Rowv = NA, scale = 'column')
```

```{r}
library(GGally)

df <- mtcars[,c(1,3:6)]
cor(df)
cor.test(df$mpg, df$wt)
plot(df)
ggcorr(df)
ggpairs(df)

```

```{r}
df <- economics
ggplot(df, aes(date, pop)) +
    geom_line(color = 'green', size = 1)

ggplot(df, aes(date, pop)) +
    geom_line(aes(size = uempmed / pop))

ggplot(df, aes(date, psavert)) +
    geom_line() +
    stat_smooth()






```
```{r}
veri <- data.frame(
    id = seq(1,60),
    ogrenciler = paste('Ogrenci', seq(60), sep = '_'),
    notlar = sample(seq(10, 100), 60, replace = T)
)

ggplot(veri, aes(x = factor(id), y = notlar)) +
    geom_bar(stat = 'identity') +
    ylim(-100, 120) +
    theme_minimal() +
    theme(
        axis.text = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        plot.margin = unit(rep(-2, 4), 'cm')
    ) +
    coord_polar(start = 0)





```

```{r}
library(treemap)

df <- data.frame(
  gruplar = c("grup_1", "grup_2","grup_3"),
  degerler = c(10, 90, 60)
  
)
 
df

treemap(df, index = "gruplar", vSize = "degerler", type ="index")

```

```{r}


df<- diamonds
df <- select(diamonds, cut, color, price)

df <- data.frame(
  gruplar = c(rep("grup_1", 4),
               rep("grup_2", 2),
               rep("grup_3", 3)),
  
  alt_gruplar = paste("alt_grup", c(1,2,3,4,1,2,1,2,3), sep = "_"),
  
  degerler = c(13,5,22,12,11,4,2,5,6)
  
)

df

treemap(df, index = c("cut","color"), 
        vSize = "price", 
        type ="index",
        fontsize.labels = c(20,13),
        fontcolor.labels = c("white","black"),
        bg.labels = c("transparent"),
        align.labels = list(
          c("center", "center"),
          c("right","bottom")
          
        ),
        border.col = c("black","white"),
        border.lwds = c(5,2)
        
        
        
        )

```