---
title: "Statistic"
author: "Cihan ERMAN"
date: "5/25/2019"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hipotez nedir?

H0: M  >= 170  
H1: M  <  170

## Statistic with R
```{r}

olcumler <- c(17, 160, 234, 149, 145, 107, 197, 75, 201, 225, 211, 119, 
              157, 145, 127, 244, 163, 114, 145,  65, 112, 185, 202, 146,
              203, 224, 203, 114, 188, 156, 187, 154, 177, 95, 165, 50, 110, 
              216, 138, 151, 166, 135, 155, 84, 251, 173, 131, 207, 121, 120)

summary(olcumler)
```
```{r}
hist(olcumler)
library(ggpubr)
ggqqplot(olcumler)
shapiro.test(olcumler)
t.test(olcumler, mu = 170, alternative = 'less', conf.level = 0.95)
library(inferr)
df <- data.frame(olcumler)
infer_os_t_test(df, olcumler, mu = 170, type = all)
```


```{r}
library(DescTools)
SignTest(df$olcumler, mu = 170)
```
500 kisi dis merada reklamlara tiklamis.
40 tanesi alisveris.
Donusum orani: 40/500 = 0,08
n > 30
```{r}
prop.test(x = 40, n = 500, p = 0.05, alternative = 'two.sided')
```

Hipotez nedir?

H0: M1  =  M2
H1: M1 !=  M2

```{r}
iki_ornek_veri <- data.frame(
  
  A = c(30,27,21,27,29,30,20,20,27,32,35,22,24,23,25,27,23,27,23,
        25,21,18,24,26,33,26,27,28,19,25),
  
  B = c(37,39,31,31,34,38,30,36,29,28,38,28,37,37,30,32,31,31,27,
        32,33,33,33,31,32,33,26,32,33,29)
)

library(funModeling)
profiling_num(iki_ornek_veri)
library(tidyverse)
ggplot(iki_ornek_veri, aes(A, B)) +
    geom_boxplot()

View(iki_ornek_veri)

A <- data.frame(degerler = iki_ornek_veri$A, sinif = "A")
B <- data.frame(degerler = iki_ornek_veri$B, sinif = "B")

AB <- rbind(A,B)

ggplot(AB, aes(sinif, degerler, fill = sinif)) +
    geom_boxplot()

```
```{r}
ggplot(AB, aes(degerler, fill = sinif)) +
    geom_histogram(color = "black", binwidth = 5, alpha = 0.5) +
    facet_grid(sinif ~.)

ggplot(AB, aes(degerler, fill = sinif)) +
    geom_histogram(aes(y = ..density..), color = "black", binwidth = 5, alpha = 0.5) +
    geom_density(alpha = 0.3) +
    facet_grid(sinif ~.)

apply(iki_ornek_veri, 2, shapiro.test)
shapiro.test(AB[AB$sinif == "A",]$degerler)
shapiro.test(AB[AB$sinif == "B",]$degerler)
```

```{r}
library(car)
LeveneTest(AB$degerler ~ AB$sinif, center = mean)
```





























